export const PGLITE_CLIENT = Symbol("PGLITE_CLIENT");
export const DRIZZLE_CLIENT = Symbol("DRIZZLE_CLIENT");
export const TODO_REPOSITORY = Symbol("TODO_REPOSITORY");
export const TODO_USE_CASE_DEPENDENCIES = Symbol("TODO_USE_CASE_DEPENDENCIES");
export const LIST_TODOS_USE_CASE = Symbol("LIST_TODOS_USE_CASE");
export const CREATE_TODO_USE_CASE = Symbol("CREATE_TODO_USE_CASE");
export const UPDATE_TODO_COMPLETED_USE_CASE = Symbol("UPDATE_TODO_COMPLETED_USE_CASE");
export const DELETE_TODO_USE_CASE = Symbol("DELETE_TODO_USE_CASE");
